/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StockRouteImport } from './routes/stock'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/buy': typeof BuyRoute
  '/expenses': typeof ExpensesRoute
  '/history': typeof HistoryRoute
  '/reports': typeof ReportsRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/buy': typeof BuyRoute
  '/expenses': typeof ExpensesRoute
  '/history': typeof HistoryRoute
  '/reports': typeof ReportsRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/buy': typeof BuyRoute
  '/expenses': typeof ExpensesRoute
  '/history': typeof HistoryRoute
  '/reports': typeof ReportsRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/buy'
    | '/expenses'
    | '/history'
    | '/reports'
    | '/sell'
    | '/settings'
    | '/stock'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/buy'
    | '/expenses'
    | '/history'
    | '/reports'
    | '/sell'
    | '/settings'
    | '/stock'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/buy'
    | '/expenses'
    | '/history'
    | '/reports'
    | '/sell'
    | '/settings'
    | '/stock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  BuyRoute: typeof BuyRoute
  ExpensesRoute: typeof ExpensesRoute
  HistoryRoute: typeof HistoryRoute
  ReportsRoute: typeof ReportsRoute
  SellRoute: typeof SellRoute
  SettingsRoute: typeof SettingsRoute
  StockRoute: typeof StockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  BuyRoute: BuyRoute,
  ExpensesRoute: ExpensesRoute,
  HistoryRoute: HistoryRoute,
  ReportsRoute: ReportsRoute,
  SellRoute: SellRoute,
  SettingsRoute: SettingsRoute,
  StockRoute: StockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
